-- Automatically generated by Gerwin
--
-- Project Documentazione
-- From file: /home/user/public_html/git/5BIT/manuali/documenti.ger
-- By: Picchiottino Roberto per 5bit as 2018-2019
--
-- Using output format: mysql



CREATE TABLE argomenti (
      id_argomento     int PRIMARY KEY AUTO_INCREMENT,
      nome     varchar(255),
      descrizione     text,
      id_padre    int NOT NULL
);






CREATE TABLE comandi (
      id_comando     int PRIMARY KEY AUTO_INCREMENT,
      nome     varchar(255),
      destrizione     text,
      sintassi     text,
      id_argomento     int NOT NULL
);






CREATE TABLE esempi (
      id     int PRIMARY KEY AUTO_INCREMENT,
      testo     text,
      id_comando     int NOT NULL
);






ALTER TABLE argomenti ADD FOREIGN KEY (id_padre) REFERENCES argomenti (id_argomento);


ALTER TABLE comandi ADD FOREIGN KEY (id_argomento) REFERENCES argomenti (id_argomento);


ALTER TABLE esempi ADD FOREIGN KEY (id_comando) REFERENCES comandi (id_comando);



